### ISSUE TITLE
Stock Delivery Internal 

### ISSUE THREAD

**Issue by ccandito** [OCA/stock-logistics-workflow#383] opened 2017-10-30 08:43 UTC
Dear All,
I've tried to use this app and a short dump's occurred.
Please find below its system log
regards
claudio candito

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/sale_order_type/models/sale_order.py", line 44, in create
    return super(SaleOrder, self).create(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/sale/models/sale.py", line 274, in create
    result = super(SaleOrder, self).create(vals)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 228, in create
    thread = super(MailThread, self).create(values)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3826, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3985, in _create
    self.recompute()
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5315, in recompute
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5315, in <dictcomp>
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5211, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 910, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 996, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 976, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 967, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/delivery/models/sale_order.py", line 26, in _compute_delivery_price
    order.delivery_price = order.carrier_id.with_context(order_id=order.id).price
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 910, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1022, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 976, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 967, in _compute_value
    getattr(records, self.compute)()
  File "<decorator-gen-94>", line 2, in get_price
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/usr/lib/python2.7/dist-packages/odoo/addons/delivery/models/delivery_carrier.py", line 121, in get_price
    computed_price = self.get_shipping_price_from_so(order)[0]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by rousseldenis** [comment] 2018-05-08 21:05
@ccandito Can you confirm that this is not caused by sale_order_type module as there is no line getting through sale_delivery_internal ?

**Comment by ccandito** [comment] 2018-05-08 22:14
Dear Denis,
it could be.
I've implemented sale_order_type because it is very useful for fiscal purposes also.
What I should do?
thanks in advance
claudio candito

**Comment by rousseldenis** [comment] 2018-10-02 08:44
@ccandito Duplicate of #371

**Closed as completed by rousseldenis** 2018-10-02 08:44 UTC
