### ISSUE TITLE
[12.0]stock_picking_line_sequence sequence has a problem

### ISSUE THREAD

**Issue by qzmxs** [OCA/stock-logistics-workflow#637] opened 2020-03-10 17:39 UTC
module: stock_picking_line_sequence
version: 12.0

**Steps to reproduce**
There is a problem with the sales order sequence  related to inventory
![image](https://user-images.githubusercontent.com/55458897/76341755-70cca680-6338-11ea-8f1c-6018184cd0dc.png)

![image](https://user-images.githubusercontent.com/55458897/76341646-4d096080-6338-11ea-933d-1ddae8aaf24b.png)

**Current behavior**

**Expected behavior**

**Comment by LoisRForgeFlow** [comment] 2020-03-11 12:35
@qzmxs Are you able to reproduce this on runbot?

cc @AaronHForgeFlow I guess this is the same issue here: https://github.com/OCA/stock-logistics-workflow/issues/631.

**Comment by AaronHForgeFlow** [comment] 2020-03-11 12:52
Sames as #631 I think we should keep only one open:

I could reproduce the issue when the module sale_order_line_sequence is not installed but stock_picking_line_sequence is installed. A fix is required. I would leave the other issue opened because it was created first.

**Comment by LoisRForgeFlow** [comment] 2020-03-11 13:05
Closed in favor of https://github.com/OCA/stock-logistics-workflow/issues/631. Tracking will continue there.

**Closed as completed by LoisRForgeFlow** 2020-03-11 13:05 UTC
